### ISSUE TITLE
you are instead of your

### ISSUE THREAD

**Issue by horshacktest** [moonlightwork/remote-work-encyclopedia#33]
https://github.com/moonlightwork/remote-work-encyclopedia/blob/master/docs/land-a-job.md#where-to-find-remote-jobs

> Once your online identity is feeling polished and clear, it's time to start connecting with potential employers. Start building up your online network **before your ready** for a new job. Sign up for as many tech communities and industry-specific forums as you can, and start engaging.

should be "before you are ready"

I'm enjoying the reading :)

**Comment by horshacktest** [comment]
something in career-growth

> Modern tools enable people with a full spectrum of goals to **fulfil** their version of success without being chained to their company headquarters at a 9-5 desk.

should be _fulfill_

**Comment by philipithomas** [comment]
Thanks for reporting these!
