### ISSUE TITLE
Mobile site should show TOC above the fold

### ISSUE THREAD

**Issue by sqs** [moonlightwork/remote-work-encyclopedia#7]
![E859B4E4-D0C1-4E6A-A723-9DF867B5B5EA](https://user-images.githubusercontent.com/1976/68704853-dbfc9c80-0541-11ea-80ea-fe55105a9a5d.png)
On the mobile site it’s not clear there’s a lot of pages in the encyclopedia. It’s just a block of text and an easy-to-miss hamburger menu.

**Comment by philipithomas** [comment]
Thanks @sqs !
